### ISSUE TITLE
Can't search or add podcast

### ISSUE THREAD

**Issue by dwalker136** [kypeli/Podcatcher#18]
Popular podcasts shows 'Error receiving top list'
Search results in  Error could not get search results

Lumia 920 - Canada - Rogers

**Comment by kypeli** [comment]
I use an external service to find podcasts called gpodder.net. This error message notes that Podcatcher was unable to fetch the results from their service.

Can you please try to visit gpodder.net and see if you can access search for podcasts on their website (https://gpodder.net/search/)? 

I also tested using their functionality on Podcatcher and for me it works ok now. Is this the case for you as well? 

As for an issue, it's actually no an issue in Podcatcher. Podcatcher just reacts to the external service's error properly.
