### ISSUE TITLE
Swiping to 'Usage' pane crashes Podcatcher

### ISSUE THREAD

**Issue by stevelitchfield** [kypeli/Podcatcher#22]
After listening to a podcast (or even part of it) in the latest beta, going into Settings and trying to swipe over to Useage causes Podcatcher to crash completely.

Restarting the phone fixes the issue.

**Comment by kypeli** [comment]
Thanks for the feedback! This issue should now be fixed.

Fix is in the following commit:

https://github.com/kypeli/Podcatcher/commit/396e89fd14de4454a1fc8f9fa4ca4a933fba7a54
