### ISSUE TITLE
Resuming streamed podcast

### ISSUE THREAD

**Issue by lemixtape** [kypeli/Podcatcher#26]
In the latest version (2.2.0.0), Podcatcher is unable to remember where playback stopped. This happens when I pause the playback with the remote button or when I go into the app and pause the playback or when I launch the Music+Video app without pausing the podcast first. I therefore always find to find the spot where I left off.

I am using WP8 on an HTC 8X.

**Comment by kypeli** [comment]
This is one of the things that the latest beta (version 2.2.0.9) tries to fix. So this doesn't ever work you with the 2.2.0.9 version when you launch the Music+Video app? 

Based on my testing this should work - at least some times.

**Comment by lemixtape** [comment]
I just tested it on my HTC 8X phone. Three times, I loaded Podcatcher, launched a podcast, let it run for a minute or two and then used the Home button to exit the app and launch a song on the Music+Video app. One podcast was a video podcast and the other two were audio.
The three times I tested it, the podcasts never made it to the Play History pane. Podcatcher also never remembered where I left off the podcast and it started playing as though I had never played it before.

Before doing this, I updated to the latest version (2.2.0.9) in the Store. When I go into the app and into the About menu however, it still lists the version as 2.2.0.0. Is that normal?

**Comment by kypeli** [comment]
I tested this a bit more and maybe this is the thing that you are seeing, but I noticed that if you initially start to play a podcast and the interrupt the playback by going  to Music+Video, then there's some issue with storing the position (and seems to have some other state issues as well). But If I go back to the same episode, start playing it again and then go again to Music+Video, it seems to work better.

I don't know if this is related to what you are experiencing, but definitely something I need to look into.

Also, please note that saving and resuming the playback only works for locally downloaded episodes (thanks Windows Phone). 

Yes - the version shown in the About page shows the release number when it will be officially available - which is 2.2.0.0.

**Comment by lemixtape** [comment]
All of the test I have been doing is for streaming podcasts. So it would make sense that it would not resume properly.  Are you planning to add the capability to resume streaming podcasts?

**Comment by kypeli** [comment]
I cannot resume streamed episodes. Windows Phone will not allow that. Sorry about this. 

Because of this, I will close this issue.
