### ISSUE TITLE
Play history

### ISSUE THREAD

**Issue by lemixtape** [kypeli/Podcatcher#27]
In the latest version (2.2.0.0), Podcatcher does not put in the Play History the podcast it is playing at least 7 times out of 10. This seems to happen even more often when I switch to another audio source. It seems to completely forget that it was playing a podcast when I switched.

I am using WP8 on an HTC 8X.

**Comment by kypeli** [comment]
This is indeed an issue when interrupting the playback. But it should work reliably if you stop the playback within Podcatcher. Can you please confirm this?

**Comment by lemixtape** [comment]
The podcast shows up in the Play History if I pause it while in the app or if the screen is off and I have not exited the app. I hope you find a way to get this issue fixed!

**Comment by lemixtape** [comment]
So the only problem is when I pause the playback outside the app or when another app takes control of the sound stream.

**Comment by kypeli** [comment]
Yeah, that's actually a known issue which should be easy to have fixed.

**Comment by kypeli** [comment]
This issue was fixed in the following commit:

https://github.com/kypeli/Podcatcher/commit/00b058493028a187bc4cc20e43eeb6685feec59b
